apiVersion: apps/v1
kind: Deployment
metadata: 
  name: docker-test2
  labels: 
    app: docker-test2
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: docker-test2
  template: 
    metadata:
      labels:
        app: docker-test2
    spec: 
      containers: 
      - name: docker-test2
        image: dockerhosexyz.azurecr.io/docker-test2:v1.0.0
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: docker-test2
  labels: 
    app: docker-test2
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: docker-test2